### ISSUE TITLE
Compilation errors due to static libraries

### ISSUE THREAD

**Issue by cc2qe** [precimed/simu#5] opened 2024-05-09 16:22 UTC
I get the following error compiling from source on Ubuntu linux.

It appears that this has been solved in CreRecombinase's [fork](https://github.com/CreRecombinase/simu/commit/af55a7163d6fe102dd436f3567acb07d67091961). Suggesting a merge (I cannot make a pull request due to permissions)

```
$ mkdir build && cd build/
$ cmake ..
$ make
[  7%] Building C object libplinkio/libs/libcsv/CMakeFiles/libcsv.dir/src/libcsv.c.o
[ 15%] Linking C static library ../../../lib/libcsv.a
[ 15%] Built target libcsv
[ 23%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/bed.c.o
[ 30%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/bed_header.c.o
[ 38%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/bim.c.o
[ 46%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/bim_parse.c.o
[ 53%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/fam.c.o
[ 61%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/fam_parse.c.o
[ 69%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/file.c.o
[ 76%] Building C object libplinkio/src/CMakeFiles/libplinkio-static.dir/plinkio.c.o
[ 84%] Linking C static library ../../lib/libplinkio.a
[ 84%] Built target libplinkio-static
[ 92%] Building CXX object src/CMakeFiles/simu.dir/source.cc.o
[100%] Linking CXX executable ../bin/simu
/usr/bin/ld: attempted static link of dynamic object `/usr/lib/aarch64-linux-gnu/libboost_program_options.so.1.83.0'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/simu.dir/build.make:103: bin/simu] Error 1
make[1]: *** [CMakeFiles/Makefile2:216: src/CMakeFiles/simu.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by espenhgn** [comment] 2024-05-10 13:03
Hi @cc2qe,
Thanks for the heads up. It looks like you're on an M1/M2 Mac or some other Arm-based machine, correct?
Can you try and make a PR from a feature branch (`git checkout -b "fix-compile" && git push ...`) before making a PR here? 

Edit: I confirmed I could build your `master` branch into a working Docker image with this recipe:
```
FROM ubuntu:20.04

LABEL org.opencontainers.image.source=https://github.com/precimed/simu
LABEL org.opencontainers.image.description="Simu-Linux"
LABEL org.opencontainers.image.licenses=GPL-3.0

ENV TZ=Europe
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /tmp

RUN apt-get update && apt-get install -y ca-certificates && \
    update-ca-certificates && \
    apt-get install -y git build-essential libboost-all-dev cmake && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --recurse-submodules https://github.com/cc2qe/simu && \
    cd simu && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    cd /tmp && \
    rm -rf simu

WORKDIR /
ENTRYPOINT ["/usr/local/bin/simu"]
```

building as:
```
docker build --platform linux/arm64 -t simu -f Dockerfile .
```

invoking:
```
docker run --platform=linux/arm64 --rm -it --mount type=bind,source=${PWD},target=/home simu:latest --help
SIMU v0.9.4 - library for simulation of GWAS summary statistics:
  -h [ --help ]             produce this help message
...
```
(and similar with `--platform=linux/amd64`). 

So a PR would be welcome!

**Comment by cc2qe** [comment] 2024-05-17 13:01
Thanks, I tried making a PR last week but permissions were restricted to collaborators only.

If you are able to change this, I will try again.

**Comment by espenhgn** [comment] 2024-05-21 08:05
That's odd with the permissions issue, and I can not find a setting to change it. 
I've moved yours and the other's changesets to a feature branch and opened a PR here: #6. 
I also added a Dockerfile and build instructions. Do you have other things to add? If so, I can try and incorporate it.

**Comment by ofrei** [comment] 2024-05-21 09:03
The changes in PR #6 look fine, please merge if the build works well!

**Comment by espenhgn** [comment] 2024-05-21 09:32
Ok, the PR is now merged, closing this.

**Closed as completed** 2024-05-21 09:31 UTC
